apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-bfnw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-bfnw
    app.kubernetes.io/part-of: test-app-aiyi
  name: test-component-bfnw
  namespace: build-e2e-hacbs-bqmi
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-bfnw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-bfnw
    spec:
      containers:
      - image: quay.io/mkovarik/test-images:b76063a67a4541de9969424bcc79b100
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
